name = "murder-mystery-pages-local"
compatibility_date = "2026-06-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "murder-mystery-pages-local"
database_id = "00000000-0000-0000-0000-000000000000"
